//@version=4
study(title="ATR with RSI by KSH", overlay=true)

// Inputs
a = input(2, title="Key Value. 'This changes the sensitivity'")
c = input(14, title="ATR Period")
rsiLength = input(14, title="RSI Length")

xATR = atr(c)
nLoss = a * xATR

xATRTrailingStop = 0.0
xATRTrailingStop := 
   iff(close > nz(xATRTrailingStop[1], 0) and close[1] > nz(xATRTrailingStop[1], 0), 
      max(nz(xATRTrailingStop[1]), close - nLoss),
   iff(close < nz(xATRTrailingStop[1], 0) and close[1] < nz(xATRTrailingStop[1], 0), 
      min(nz(xATRTrailingStop[1]), close + nLoss), 
   iff(close > nz(xATRTrailingStop[1], 0), 
      close - nLoss, close + nLoss)))

ema   = ema(close,1)
above = crossover(ema, xATRTrailingStop)
below = crossover(xATRTrailingStop, ema)

buy  = close > xATRTrailingStop and above 
sell = close < xATRTrailingStop and below

// Calculate RSI
rsiValue = rsi(close, rsiLength)

plotshape(buy,  title="Buy",  text='Buy',  style=shape.labelup,   location=location.belowbar, color=color.green, textcolor=color.white, transp=0, size=size.tiny)
plotshape(sell, title="Sell", text='Sell', style=shape.labeldown, location=location.abovebar, color=color.red,   textcolor=color.white, transp=0, size=size.tiny)


CloseShort = iff(close > xATRTrailingStop and below and (rsiValue[0] < 55 or rsiValue[0] == 55 or rsiValue[0] > 45 or rsiValue[0] == 45), true, false)

CloseLong = iff(close < xATRTrailingStop and above and (rsiValue[0] < 55 or rsiValue[0] == 55 or rsiValue[0] > 45 or rsiValue[0] == 45), true, false)
           
StartShort = iff(close > xATRTrailingStop and below and (rsiValue[0] > 55 or rsiValue[0] < 45), true, false)

StartLong = iff(close < xATRTrailingStop and above and (rsiValue[0] > 55 or rsiValue[0] < 45), true, false)

CloseShort_msg = CloseShort ? "CloseShort" : ""
CloseLong_msg = CloseLong ? "CloseLong" : ""
StartShort_msg = StartShort ? "StartShort" : ""
StartLong_msg = StartLong ? "StartLong" : ""

var Decision = CloseShort_msg + CloseLong_msg + StartShort_msg + StartLong_msg

if CloseShort or CloseLong or StartShort or StartLong
    alert(Decision, alert.freq_once_per_bar_close)

   // 트레일링 스탑 값 플로팅
plot(xATRTrailingStop, title="Trailing Stop", color=color.orange, linewidth=2, transp=0)
